version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docanalyzer
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: